spring:
  datasource:
    url: jdbc:postgresql://localhost:8060/cymark-delivery
    username: postgres
    password: cymark1425
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

